-- CREATE DATABASE IF NOT EXISTS DB_PANOL;
-- USE DB_PANOL;
-- DROP DATABASE IF EXISTS DB_PANOL;

-- DROP TABLE IF EXISTS Inventario;
CREATE TABLE IF NOT EXISTS Inventario(
id BIGINT NOT NULL AUTO_INCREMENT,
nombre VARCHAR(150) NOT NULL,
descripcion VARCHAR(150) NOT NULL,
ubicacion VARCHAR(50) NOT NULL DEFAULT 'DEPOSITO',
foto VARCHAR(100) NOT NULL DEFAULT 'img_item_default',
estado TINYINT(1) NOT NULL DEFAULT 1,
CONSTRAINT PK_Inventario PRIMARY KEY(id),
CONSTRAINT CK_Inventario_ubicacion CHECK(ubicacion='DEPOSITO' OR ubicacion='PRESTADO')
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=1;

-- DROP TABLE IF EXISTS Usuario;
CREATE TABLE IF NOT EXISTS Usuario(
nombreUsuario CHAR(150) NOT NULL,
clave VARCHAR(128) NOT NULL,
nombre VARCHAR(150) NOT NULL,
apellido VARCHAR(150) NOT NULL,
rol VARCHAR(50) NOT NULL DEFAULT 'PRESTATARIO',
foto VARCHAR(100) NOT NULL DEFAULT 'img_avatar_default',
estado TINYINT(1) NOT NULL DEFAULT 1,
CONSTRAINT PK_Usuario PRIMARY KEY(nombreUsuario),
CONSTRAINT CK_Usuario_rol CHECK(rol = 'ADMIN' OR rol = 'PRESTATARIO')
)ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 AUTO_INCREMENT = 1;

-- DROP TABLE IF EXISTS Admin;
CREATE TABLE IF NOT EXISTS Admin(
id BIGINT NOT NULL AUTO_INCREMENT,
estado TINYINT(1) NOT NULL DEFAULT 1,
id_usuario CHAR(150) NOT NULL,
CONSTRAINT PK_Admin PRIMARY KEY(id),
CONSTRAINT FK_Admin_Usuario FOREIGN KEY(id_usuario) REFERENCES Usuario(nombreUsuario),
CONSTRAINT UK_Admin_idusuario UNIQUE(id_usuario)
)ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 AUTO_INCREMENT = 1;

-- DROP TABLE IF EXISTS Prestatario;
CREATE TABLE IF NOT EXISTS Prestatario(
id BIGINT NOT NULL AUTO_INCREMENT,
estado TINYINT(1) NOT NULL DEFAULT 1,
id_usuario CHAR(150) NOT NULL,
CONSTRAINT PK_Prestatario PRIMARY KEY(id),
CONSTRAINT FK_Prestatario_Usuario FOREIGN KEY(id_usuario) REFERENCES Usuario(nombreUsuario),
CONSTRAINT UK_Prestatario_idusuario UNIQUE(id_usuario)
)ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 AUTO_INCREMENT = 1;

-- DROP TABLE IF EXISTS Prestamo
CREATE TABLE IF NOT EXISTS Prestamo(
id BIGINT NOT NULL AUTO_INCREMENT,
fechaSolicitud DATETIME(6) NOT NULL,
fechaDevolucion DATETIME(6) NOT NULL,
estadoPrestamo VARCHAR(50) NOT NULL DEFAULT 'ACEPTADO',
estado TINYINT(1) NOT NULL DEFAULT 1,
id_inventario BIGINT NOT NULL,
id_prestatario BIGINT NOT NULL,
CONSTRAINT PK_Prestamo PRIMARY KEY(id),
CONSTRAINT FK_Prestamo_Inventario FOREIGN KEY(id_inventario) REFERENCES Inventario(id),
CONSTRAINT FK_Prestamo_Prestatario FOREIGN KEY(id_prestatario) REFERENCES Prestatario(id),
CONSTRAINT CK_Prestamo_estadoPrestamo CHECK(estadoPrestamo = 'ACEPTADO' OR estadoPrestamo = 'CONCLUIDO')
)ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 AUTO_INCREMENT = 1;
